version: '3.8'

services:
  strapi:
    build:
      context: ./my-strapi-app
    ports:
      - "1337:1337"
    environment:
      DATABASE_CLIENT: sqlite
      DATABASE_NAME: data
    volumes:
      - ./my-strapi-app:/usr/src/app
    depends_on:
      - n8n
    networks:
      - strapi

  n8n:
    build:
      context: ./my-n8n-app
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=sqlite
      - DB_SQLITE_DATABASE=/root/n8n/data/database.sqlite
    volumes:
      - ./my-n8n-app:/root/n8n
    networks:
      - strapi
networks:
  strapi:
    name: Strapi
    driver: bridge